#yaml document start with ---
---
- # this minus is required in yaml it indicates list of items. playbook contains the list of plays and every play will be a dictonary
#host where you want to run your playbook.
  hosts: client, clientubuntu
#vars: variable that will apply to the play
  vars: #is a keywoad
    motd_centos: "Welcome to Redhat ansible rocks2\n"
    motd_ubuntu: "Welcome to ubunut ansible rock2\n"
  tasks:
    - name: set a fact
      set_fact:
        our_fact: Ansible Rocks!
        ansible_distribution: "{{ansible_distribution | upper }}"
    - name: show our face
      debug:
        msg: "{{ our_fact }}"
    - name: show ansible distribution 
      debug:
        msg: "{{ansible_distribution}}"