#yaml document start with ---
---
- # this minus is required in yaml it indicates list of items. playbook contains the list of plays and every play will be a dictonary
#host where you want to run your playbook.
  hosts: client
#vars: variable that will apply to the play
  vars: #is a keywoad
    motd_centos: "Welcome to Redhat ansible rocks2\n"
    motd_ubuntu: "Welcome to ubunut ansible rock2\n"
  tasks:
    - name: set a fact
      fetch:
        src: /tmp/test.txt
        dest: /tmp/



        #Copied a file from node to ansible master